workflows:
  ios-release:
    name: BallIQ iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: CodeMagic
    environment:
      ios_signing:
        provisioning_profiles:
          - balliq_dist
        certificates:
          - balliq_dist
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        APP_STORE_APPLE_ID: 6785253664
      node: v22.14.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Capacitor sync iOS
        script: npx cap sync ios
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID")
          NEW_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          agvtool new-version -all $NEW_BUILD_NUMBER

      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true